[workspace]
resolver = "2"
members = ["crates/smartkey-core", "crates/smartkey-py", "crates/smartkey-win", "crates/smartkey-mac"]

[workspace.dependencies]
aho-corasick = "1"
bitflags = "2"
memmap2 = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
rand = "0.8"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3
