[package]
name = "smartkey-core"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = { workspace = true }
memmap2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
